# docker-compose.yml

services:

  postgres:
    image: postgres:15-alpine
    container_name: inventory_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: inventory_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api

    container_name: inventory_api

    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/inventory_db
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      ALGORITHM: ${ALGORITHM}

      APP_ENV: ${APP_ENV}
      DEBUG: ${DEBUG}
      LOG_LEVEL: ${LOG_LEVEL}

      PYTHONPATH: /app

      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_EXPERIMENT_NAME: ${MLFLOW_EXPERIMENT_NAME}

      DEFAULT_LEAD_TIME_DAYS: ${DEFAULT_LEAD_TIME_DAYS}
      DEFAULT_SERVICE_LEVEL: ${DEFAULT_SERVICE_LEVEL}
      FORECAST_HORIZON_DAYS: ${FORECAST_HORIZON_DAYS}

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - models_data:/app/models

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.frontend

    container_name: inventory_frontend

    ports:
      - "3000:80"

    environment:
      VITE_API_URL: http://localhost:8000

    depends_on:
      - api

volumes:
  postgres_data:
  models_data: